entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true
serversTransport:
  insecureSkipVerify: true
  rootCAs:
    - ./certs/proxmox_cert.pem

certificatesResolvers:
  cloudflare:
    acme:
      email: mikecozier@hotmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}

metrics:
  prometheus:
    entryPoint: websecure

http:
  routers:
    proxmox:
      entryPoints:
        - "websecure"
      rule: "Host(`proxmox.michaelcozierdns.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls:
        certResolver: cloudflare
        certificates:
          - certFile: /etc/traefik/certs/proxmox_cert.pem
      service: proxmox
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.100:8006"
        passHostHeader: true
        serversTransport: 
          proxmox-transport:
            insecureSkipVerify: true
            caFiles:
              - /etc/traefik/certs/proxmox_cert.pem
            serverName: "192.168.1.100"
          
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        stsSeconds: 31536000
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
